// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlcfpteCLtMS-HxJ7R1iCjDyynaqjoIZ0',
    appId: '1:92863232638:web:97b2d0e5d2b1e873fc762f',
    messagingSenderId: '92863232638',
    projectId: 'news-e9a94',
    authDomain: 'news-e9a94.firebaseapp.com',
    storageBucket: 'news-e9a94.firebasestorage.app',
    measurementId: 'G-21YEFG6JCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfK-zk_acpvLsQ1emHxiVNMhgIsbRDFgI',
    appId: '1:92863232638:android:b9d90cb937feaf19fc762f',
    messagingSenderId: '92863232638',
    projectId: 'news-e9a94',
    storageBucket: 'news-e9a94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAETxlWchWPckIlqj6DkZ_RIF-35SO40nI',
    appId: '1:92863232638:ios:462ffc50b63494b9fc762f',
    messagingSenderId: '92863232638',
    projectId: 'news-e9a94',
    storageBucket: 'news-e9a94.firebasestorage.app',
    iosClientId: '92863232638-jgaodnnof8kvj804rstbid0ahfva0f4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAETxlWchWPckIlqj6DkZ_RIF-35SO40nI',
    appId: '1:92863232638:ios:462ffc50b63494b9fc762f',
    messagingSenderId: '92863232638',
    projectId: 'news-e9a94',
    storageBucket: 'news-e9a94.firebasestorage.app',
    iosClientId: '92863232638-jgaodnnof8kvj804rstbid0ahfva0f4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlcfpteCLtMS-HxJ7R1iCjDyynaqjoIZ0',
    appId: '1:92863232638:web:9f1fbb27dd6f567ffc762f',
    messagingSenderId: '92863232638',
    projectId: 'news-e9a94',
    authDomain: 'news-e9a94.firebaseapp.com',
    storageBucket: 'news-e9a94.firebasestorage.app',
    measurementId: 'G-194KP9LYCC',
  );
}
